config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root to: "flats#index"
   resources :flats
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

def index
  @flats = Flat.all
end

def show
  @flat = Flat.find(params[:id])
end

def new
  @flat = Flat.new
end

def create
  @flat = Flat.new(flat_params)
  if @flat.save
    redirect_to flat_path(@flat)
  else
    render :new, status: :unprocessable_entity
  end
end

def update
  @flat = Flat.find(params[:id])
  if @flat.update(flat_params)
    redirect_to flat_path(@flat)
  else
    render :new, status: :unprocessable_entity
  end
end

def destroy
  @flat = Flat.find(params[:id])

  if @flat.destroy
    redirect_to flats_path, status: :see_other
  else
    # Gérer le cas où la suppression échoue
    render plain: 'La suppression a échoué', status: :unprocessable_entity
  end
end



def edit
  @flat = Flat.find(params[:id])
end


end

private

def flat_params
  params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-3">
        <div class="flat-card">
          <div class="flat-card-image">
            <img class="image" src="<%=image_path("photoappart.webp")%>">
          </div>
          <div class="flat-card content">
            <h4 class="name">  <%= flat.name  %> </h4>
          </div>
            <p> <%= flat.description %></p>
              <i class="fa-solid fa-euro-sign"></i>
              <span> <%= flat.price_per_night %> </span>
              <i class="fa-solid fa-people-line"></i>
              <span> <%= flat.number_of_guests %> </span>
          <div class="flat-card action">
            <%= link_to "En savoir plus", flat_path(flat) %>
            <%= link_to "Modifier", edit_flat_path(flat) %>
            <%= link_to "Supprimer", flat_path(flat),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "ms-3 text-danger" %> </div>
      </div>
       <div class="flat-card action">
         <%= link_to "Ajouter", new_flat_path(flat) %>
       </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
lll
   <%= link_to "Supprimer", flats_path(params[:id]),
      data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" },
      class: "ms-3 text-danger" %> </div>

<%= link_to "Modifier", edit_flat_path(params[:id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
 <div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h4 class="text-white">Collapsed content</h4>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>